### ISSUE TITLE
Use with Angular 1.1.5

### ISSUE THREAD

**Issue by Gwash3189** [thewildpendulum/angular-phonegap-seed#1]
Thanks for making this project. I've recently used it in a project and it's a great starting point. Although with the release of angular 1.1.5 the app.js file is no longer needed when using cordova 2.7.0. 

Angular actually bootstraps it self. I am not 100% on how but i believe that angular either listening for the DeviceReady event it self, or cordova fires another, recognized event.

**Comment by thewildpendulum** [comment]
Thanks for the update. I'll try to get to this soon, but feel free to submit a pull request in the meantime.

**Comment by thewildpendulum** [comment]
You're right, Angular does bootstrap itself, though it does so independently of Cordova. My original thinking in app.js was to delay Angular loading until the Cordova APIs were available. After reading up on the issue, however, I've included a better method for handling that.

**Comment by thewildpendulum** [comment]
Fixed in b1d62249d7c4f8dc6a17f5749d768d3756a53a14

**Comment by Gwash3189** [comment]
Hey @thewildpendulum,
sorry for the late reply, thanks for looking into that.
