### ISSUE TITLE
Make Into a Yeoman Generator

### ISSUE THREAD

**Issue by KraigWalker** [thewildpendulum/angular-phonegap-seed#2]
I just wasted 2 hours trying to get Yeoman's generator-angular to play nice with the phonegap project. This could be really useful in the wider eco-system.

**Comment by thewildpendulum** [comment]
That's definitely been on my radar. The very short roadmap is to rebuild with PhoneGap 3, attempt to use ng-animate to get some mobile-like view transitions, and then write the generator.

Considering my limited time, I might skip animations for now, but if I'm going to release it, I wouldn't want to leave out something that people really want. So your feedback is definitely welcome.

**Comment by thewildpendulum** [comment]
Ask and you shall receive: https://github.com/thewildpendulum/gaps
