### ISSUE TITLE
Same code is not working for Windows phone

### ISSUE THREAD

**Issue by monikaagg** [thewildpendulum/angular-phonegap-seed#5]
I am trying to compile my code on windows phone but this same code is not working my view is not loaded. Can you help me out what can be the issue?

**Comment by thewildpendulum** [comment]
Unfortunately, I don't have any experience with developing in a Windows environment. So, I won't be of much help.

When you do you figure out your problem, it would be great if you could update this issue or open a pull request so that other developers can benefit from what you learn.
